// Generated by life-data/scripts/generate-core-contract.ts. Contract SHA-256: 0b723d74952079734ac03ed2441fa6277352a452089f67f2a85a8172443ff84a
// Do not edit; change core/contract/core.json and regenerate.
export const CORE_CONTRACT_HASH = "0b723d74952079734ac03ed2441fa6277352a452089f67f2a85a8172443ff84a";
export type JSONValue = unknown;
export type Row = Record<string, JSONValue>;
export type Count = number;
export type FilterOp = "eq" | "ne" | "contains" | "gt" | "gte" | "lt" | "lte" | "empty" | "not_empty";
export type FilterValue = string | number | boolean | null;
export type SortDirection = "asc" | "desc";
export type Sort = { column: string; direction: SortDirection };
export type Filter = { column: string; op: FilterOp; value?: FilterValue };
export type View = { table: string; columns?: string[]; filters?: Filter[]; sort?: Sort[]; limit?: Count; offset?: Count; trash?: boolean; search?: string };
export type OptionDef = { v: string; d?: string; sort?: number };
export type PropertyFlag = number | boolean;
export type Property = { tbl?: string; col: string; label?: string | null; sort?: number | null; type?: string | null; required?: PropertyFlag | null; default_value?: string | null; options?: OptionDef[] | null; options_sql?: string | null; min_items?: number | null; max_items?: number | null; pattern?: string | null; ref_table?: string | null; derived_by?: string | null; inputs?: string[] | null; immutable?: PropertyFlag | null; deprecated?: PropertyFlag | null; description?: string | null; source?: string | null; source_ref?: string | null; id?: string };
export type Violation = { col: string; rule: string; message: string };
export type WriteViolation = { col: string; rule: string; message: string; tbl: string; row_id: string | null };
export type Catalog = { tables: Row[]; properties: Property[]; rules: Row[] };
export type WorkspaceRow = { record: Row; label: string };
export type SyncSettings = { maxRows?: Count; tables?: Record<string, boolean> };
export type SyncResult = { pulled: Count; pushed: Count; skipped: string[]; rejected: Row[] };
export type SyncStatus = { lastSuccessfulSync: string | null; pendingUiEdits: Count; rejected: Count; skippedTables: string[] };
export type UsagePeriod = { start: string; end: string; anchor_day: Count };
export type UsageMetricKind = "cumulative" | "gauge";
export type UsageMetric = { kind: UsageMetricKind; unit: string; used: number | null; allowance: number | null; cap: number | null; alert_at: number[]; measured_at: string | null };
export type UsageCap = { metric: string; used: number; cap: number; resets_at: string };
export type UsagePrincipal = { id: string; label: string | null; kind: string; rows_read: number; rows_written: number; requests: number };
export type UsageSummary = { period: UsagePeriod; measured_at: string | null; capped: UsageCap | null; metrics: Record<string, UsageMetric>; by_principal: UsagePrincipal[] };
export type HubNotification = { seq: Count; id: string; created_at: string; producer: string; type: string; severity: string; title: string; body: string; data: JSONValue; read_at: string | null };
export type NotificationFeed = { notifications: HubNotification[]; next_cursor: null; latest_cursor: Count; unread_count: Count };
export type NotificationPresentation = { notifications: HubNotification[]; baseline: Count };
export type NotificationReadSelector = { ids?: string[]; through?: Count };
export type NotificationReadResult = { unread_count: Count };
export type EmptyArgs = {  };
export type EndpointArgs = { endpoint: string };
export type SyncArgs = { endpoint: string; maxRows?: Count; tables?: Record<string, boolean> };
export type OptionsArgs = { table: string; column: string };
export type WriteArgs = { table: string; patch: Row; expectedUpdatedAt?: string };
export type NotificationReadArgs = { endpoint: string; selector: NotificationReadSelector };
export type NotificationPresentationArgs = { feed: NotificationFeed; baseline: Count | null };
export type SearchArgs = { text: string; table?: string; limit?: Count; offset?: Count };
export type SearchHit = { table: string; id: string; label: string; excerpt: string };
/// columns is SQL projection and may omit id, updated_at and hidden fields; fetch a full row before editing. For visible layout only, omit columns when querying rows.
export type SavedViewDefinition = { version: Count; columns?: string[]; filters?: Filter[]; sort?: Sort[]; search?: string; trash?: boolean; widths?: Record<string, number> };
export type SavedViewRecord = { id: string; name: string; tbl: string; updated_at: string | null; deleted_at: string | null; definition: SavedViewDefinition | null; view: View | null; unavailable: string | null };
export type SavedViewList = { views: SavedViewRecord[]; unavailable: string | null };
export type ListViewsArgs = { table: string; trash?: boolean };
/// expectedUpdatedAt is required when id is supplied; omit both to create a new view.
export type SaveViewArgs = { table: string; name: string; definition: SavedViewDefinition; id?: string; expectedUpdatedAt?: string };
export type DeleteViewArgs = { id: string; expectedUpdatedAt: string };
export type WriteabilityArgs = { table: string };
/// Advisory table guards only. writeRow rechecks under its writer transaction; coverage is not a simultaneous or current remote snapshot.
export type Writeability = { writable: boolean; reason: WriteViolation | null };
/// Transient read-only hub row, including all locally known physical columns. deleted explicitly identifies tombstones. Never pass this record to the local writer or imply it is locally replicated.
export type RemoteRecord = { record: Row; label: string; deleted: boolean };
/// One online page in source ID order; default limit 50, maximum 200. Pass nextCursor unchanged; omit cursor to refresh. No text search, arbitrary filters, sorting, count or snapshot guarantee.
export type RemoteRowsArgs = { endpoint: string; table: string; limit?: Count; cursor?: string };
/// Transient page including tombstones. A full page may require an empty terminal request. Across a changing hub, clients deduplicate repeated record IDs before keyed rendering, replacing the displayed record with the later response; this does not establish a snapshot.
export type RemoteRowsPage = { rows: RemoteRecord[]; nextCursor: string | null };
/// One online ID lookup using the source column collation; the returned ID retains its stored spelling.
export type RemoteRowArgs = { endpoint: string; table: string; id: string };
export type RemoteRowResult = { row: RemoteRecord | null };
export type UndoKind = "create" | "edit" | "trash" | "restore";
/// One volatile last saved change in this opened workspace session. receiptId is opaque; clients never supply inverse data. Each autosave replaces the previous action.
export type UndoAction = { receiptId: string; table: string; rowId: string; kind: UndoKind };
export type UndoStatus = { action: UndoAction | null };
export type UndoArgs = { receiptId: string };
export type EnrollmentApprovalArgs = { fingerprint: string; name: string };
export type EnrollmentPolicy = { pollIntervalSeconds: Count; timeoutSeconds: Count; maxResponseBytes: Count };
export type EnrollmentApproval = { path: string; approvalCode: string; deviceName: string; policy: EnrollmentPolicy };
export type ReplicaIneligibilityCode = "full_scope_required" | "invalid_capabilities" | "schema_unavailable" | "replica_sync_disabled";
export type ReplicaIneligibility = { code: ReplicaIneligibilityCode; message: string };
export type ReplicaEligibility = { allowed: boolean; reason: ReplicaIneligibility | null };
export type SessionInfo = { name: string; scopes: string[]; replica: ReplicaEligibility };
export type SessionDataArgs = { data: JSONValue };
/// Host supplies HTTP status, bounded parsed JSON on 200 or null otherwise. Never derive status from error strings. Optional Retry-After delay is parsed by the host without platform clocks in core.
export type SessionReply = { status: Count; data: JSONValue; retryAfterSeconds?: Count };
export type EnrollmentPollArgs = { reply: SessionReply; expectedFingerprint: string };
export type EnrollmentPollState = "pending" | "approved";
/// Approved means the candidate identity was authenticated. Hosts must also require session.replica.allowed before installing it for replica use. Pending never distinguishes an unapproved token from a revoked one.
export type EnrollmentPollResult = { state: EnrollmentPollState; session: SessionInfo | null; retryAfterSeconds: Count | null };
export type SessionRevocationState = "revoked" | "unauthorized";
/// Unauthorized is not proof that an unregistered approval URL has been cancelled; a later browser approval remains possible.
export type SessionRevocationResult = { state: SessionRevocationState };
export type ReferenceSourcesArgs = { table: string };
export type ReferenceSource = { table: string; column: string; label: string; type: "ref" | "multi_ref"; incomplete: boolean };
export type ReferencedByArgs = { table: string; rowId: string; sourceTable: string; column: string; limit?: Count; offset?: Count };
export type ReferencedByPage = { source: ReferenceSource; rows: WorkspaceRow[]; nextOffset: Count | null };

export interface CoreOperations {
  catalog: { args: EmptyArgs; result: Catalog };
  /// columns is SQL projection and may omit id, updated_at and hidden fields; fetch a full row before editing. For visible layout only, omit columns when querying rows.
  rows: { args: View; result: WorkspaceRow[] };
  options: { args: OptionsArgs; result: string[] };
  write: { args: WriteArgs; result: Row };
  status: { args: EmptyArgs; result: SyncStatus };
  sync: { args: SyncArgs; result: SyncResult };
  serviceUsage: { args: EndpointArgs; result: UsageSummary };
  serviceNotifications: { args: EndpointArgs; result: NotificationFeed };
  markNotificationsRead: { args: NotificationReadArgs; result: NotificationReadResult };
  notificationPresentation: { args: NotificationPresentationArgs; result: NotificationPresentation };
  search: { args: SearchArgs; result: SearchHit[] };
  /// columns is SQL projection and may omit id, updated_at and hidden fields; fetch a full row before editing. For visible layout only, omit columns when querying rows.
  listViews: { args: ListViewsArgs; result: SavedViewList };
  /// expectedUpdatedAt is required when id is supplied; omit both to create a new view.
  saveView: { args: SaveViewArgs; result: SavedViewRecord };
  deleteView: { args: DeleteViewArgs; result: SavedViewRecord };
  /// Read-only advisory. Always use write for the transactionally rechecked mutation.
  writeability: { args: WriteabilityArgs; result: Writeability };
  /// One bounded hub pull with no local row, checkpoint, coverage or outbox writes. A matching durable endpoint binding and local schema are required. Remote results are read-only.
  remoteRows: { args: RemoteRowsArgs; result: RemoteRowsPage };
  /// One bounded hub pull by ID; null means no matching row. Tombstones remain explicit. A matching durable endpoint binding and local schema are required.
  remoteRow: { args: RemoteRowArgs; result: RemoteRowResult };
  /// Read this handler instance's last saved change after queued session mutations settle. Closing the workspace discards the receipt. This is not a history query or a guarantee that undo will pass current validation.
  undoStatus: { args: EmptyArgs; result: UndoStatus };
  /// Undo last saved change through the ordinary validated writer, requiring the captured revision and shape. Success consumes the receipt; failure preserves it. No redo or timestamp restoration. Hosts pause autosave and preserve newer drafts for explicit review.
  undo: { args: UndoArgs; result: Row };
  /// Pure relative approval path and public fingerprint code. Hosts validate/canonicalize the endpoint and generate/hash the candidate token; core never receives it.
  enrollmentApproval: { args: EnrollmentApprovalArgs; result: EnrollmentApproval };
  /// Pure nonadmin identity validation and current full-scope replica eligibility. Dedicated manual names are allowed. No network or storage.
  validateDeviceSession: { args: SessionDataArgs; result: SessionInfo };
  /// Pure classification of one bounded session response, matching device:<fingerprint> only on approval. Hosts own deadline/cancellation and cap the returned retry delay to remaining time; never poll after the deadline.
  enrollmentPollResult: { args: EnrollmentPollArgs; result: EnrollmentPollResult };
  /// Pure classification of session POST. Only 200 with logged_out true confirms revocation; 401 is separately unauthorized, never proof that future approval is impossible.
  sessionRevocationResult: { args: SessionReply; result: SessionRevocationResult };
  /// Incoming live catalog ref/multi_ref definitions and persisted skipped-source warnings; no source row scans. Hosts load groups lazily.
  referenceSources: { args: ReferenceSourcesArgs; result: ReferenceSource[] };
  /// One bounded local incoming-reference group. Default 20 rows, maximum 100, live sources only. Target identity uses its primary-key collation, including trashed targets. Hosts ignore stale replies and re-read a row before opening it.
  referencedBy: { args: ReferencedByArgs; result: ReferencedByPage };
}
export type CoreMethod = keyof CoreOperations;
export type CoreArgs<M extends CoreMethod> = CoreOperations[M]["args"];
export type CoreResult<M extends CoreMethod> = CoreOperations[M]["result"];
export type CoreHandlers = { [M in CoreMethod]: (args: CoreArgs<M>) => CoreResult<M> | Promise<CoreResult<M>> };
