// Generated by life-data/scripts/generate-core-contract.ts. Contract SHA-256: dd24dd6ecbb094bf0ea9d391be40fb3ed008fd107b106d925ea05ab4c4aa39e2
// Do not edit; change core/contract/core.json and regenerate.
export const CORE_CONTRACT_HASH = "dd24dd6ecbb094bf0ea9d391be40fb3ed008fd107b106d925ea05ab4c4aa39e2";
export type JSONValue = unknown;
export type Row = Record<string, JSONValue>;
export type Count = number;
export type FilterOp = "eq" | "ne" | "contains" | "gt" | "gte" | "lt" | "lte" | "empty" | "not_empty";
export type FilterValue = string | number | boolean | null;
export type SortDirection = "asc" | "desc";
export type Sort = { column: string; direction: SortDirection; mode?: SortMode };
export type Filter = { column: string; op: FilterOp; value?: FilterValue; relative?: FilterRelative };
export type View = { table: string; columns?: string[]; filters?: Filter[]; sort?: Sort[]; limit?: Count; offset?: Count; trash?: boolean; search?: string; groups?: FilterGroup[]; calendar?: CalendarContext };
export type OptionDef = { v: string; d?: string; sort?: number };
export type PropertyFlag = number | boolean;
export type Property = { tbl?: string; col: string; label?: string | null; sort?: number | null; type?: string | null; required?: PropertyFlag | null; default_value?: string | null; options?: OptionDef[] | null; options_sql?: string | null; min_items?: number | null; max_items?: number | null; pattern?: string | null; ref_table?: string | null; derived_by?: string | null; inputs?: string[] | null; immutable?: PropertyFlag | null; deprecated?: PropertyFlag | null; description?: string | null; source?: string | null; source_ref?: string | null; id?: string; updated_at?: string | null };
export type Violation = { col: string; rule: string; message: string };
export type WriteViolation = { col: string; rule: string; message: string; tbl: string; row_id: string | null };
export type Catalog = { tables: Row[]; properties: Property[]; rules: Row[] };
export type WorkspaceRow = { record: Row; label: string };
export type SyncSettings = { maxRows?: Count; tables?: Record<string, boolean> };
export type SyncResult = { pulled: Count; pushed: Count; skipped: string[]; rejected: Row[] };
export type SyncStatus = { lastSuccessfulSync: string | null; pendingUiEdits: Count; rejected: Count; skippedTables: string[] };
export type UsagePeriod = { start: string; end: string; anchor_day: Count };
export type UsageMetricKind = "cumulative" | "gauge";
export type UsageMetric = { kind: UsageMetricKind; unit: string; used: number | null; allowance: number | null; cap: number | null; alert_at: number[]; measured_at: string | null };
export type UsageCap = { metric: string; used: number; cap: number; resets_at: string };
export type UsagePrincipal = { id: string; label: string | null; kind: string; rows_read: number; rows_written: number; requests: number };
export type UsageSummary = { period: UsagePeriod; measured_at: string | null; capped: UsageCap | null; metrics: Record<string, UsageMetric>; by_principal: UsagePrincipal[] };
export type HubNotification = { seq: Count; id: string; created_at: string; producer: string; type: string; severity: string; title: string; body: string; data: JSONValue; read_at: string | null };
export type NotificationFeed = { notifications: HubNotification[]; next_cursor: null; latest_cursor: Count; unread_count: Count };
export type NotificationPresentation = { notifications: HubNotification[]; baseline: Count };
export type NotificationReadSelector = { ids?: string[]; through?: Count };
export type NotificationReadResult = { unread_count: Count };
export type EmptyArgs = {  };
export type EndpointArgs = { endpoint: string };
export type SyncArgs = { endpoint: string; maxRows?: Count; tables?: Record<string, boolean> };
export type OptionsArgs = { table: string; column: string };
export type WriteArgs = { table: string; patch: Row; expectedUpdatedAt?: string };
export type NotificationReadArgs = { endpoint: string; selector: NotificationReadSelector };
export type NotificationPresentationArgs = { feed: NotificationFeed; baseline: Count | null };
export type SearchArgs = { text: string; table?: string; limit?: Count; offset?: Count };
export type SearchHit = { table: string; id: string; label: string; excerpt: string };
/// columns is SQL projection and may omit id, updated_at and hidden fields; fetch a full row before editing. For visible layout only, omit columns when querying rows.
export type SavedViewDefinition = { version: Count; columns?: string[]; filters?: Filter[]; sort?: Sort[]; search?: string; trash?: boolean; widths?: Record<string, number>; groups?: FilterGroup[]; timeZone?: string; dayStartMinutes?: number; actions?: RowAction[]; layout?: ViewLayoutItem[]; presentation?: ViewPresentation };
export type SavedViewRecord = { id: string; name: string; tbl: string; updated_at: string | null; deleted_at: string | null; definition: SavedViewDefinition | null; view: View | null; unavailable: string | null };
export type SavedViewList = { views: SavedViewRecord[]; unavailable: string | null };
export type ListViewsArgs = { table: string; trash?: boolean };
/// expectedUpdatedAt is required when id is supplied; omit both to create a new view.
export type SaveViewArgs = { table: string; name: string; definition: SavedViewDefinition; id?: string; expectedUpdatedAt?: string };
export type DeleteViewArgs = { id: string; expectedUpdatedAt: string };
export type WriteabilityArgs = { table: string };
/// Advisory table guards only. writeRow rechecks under its writer transaction; coverage is not a simultaneous or current remote snapshot.
export type Writeability = { writable: boolean; reason: WriteViolation | null };
/// Transient read-only hub row, including all locally known physical columns. deleted explicitly identifies tombstones. Never pass this record to the local writer or imply it is locally replicated.
export type RemoteRecord = { record: Row; label: string; deleted: boolean };
/// One online page in source ID order; default limit 50, maximum 200. Pass nextCursor unchanged; omit cursor to refresh. No text search, arbitrary filters, sorting, count or snapshot guarantee.
export type RemoteRowsArgs = { endpoint: string; table: string; limit?: Count; cursor?: string };
/// Transient page including tombstones. A full page may require an empty terminal request. Across a changing hub, clients deduplicate repeated record IDs before keyed rendering, replacing the displayed record with the later response; this does not establish a snapshot.
export type RemoteRowsPage = { rows: RemoteRecord[]; nextCursor: string | null };
/// One online ID lookup using the source column collation; the returned ID retains its stored spelling.
export type RemoteRowArgs = { endpoint: string; table: string; id: string };
export type RemoteRowResult = { row: RemoteRecord | null };
export type UndoKind = "create" | "edit" | "trash" | "restore";
/// One volatile last saved change in this opened workspace session. receiptId is opaque; clients never supply inverse data. Each autosave replaces the previous action.
export type UndoAction = { receiptId: string; table: string; rowId: string; kind: UndoKind };
export type UndoStatus = { action: UndoAction | null };
export type UndoArgs = { receiptId: string };
export type EnrollmentApprovalArgs = { fingerprint: string; name: string; profile?: string };
export type EnrollmentPolicy = { pollIntervalSeconds: Count; timeoutSeconds: Count; maxResponseBytes: Count };
export type EnrollmentApproval = { path: string; approvalCode: string; deviceName: string; policy: EnrollmentPolicy };
export type ReplicaIneligibilityCode = "full_scope_required" | "invalid_capabilities" | "schema_unavailable" | "replica_sync_disabled";
export type ReplicaIneligibility = { code: ReplicaIneligibilityCode; message: string };
export type ReplicaEligibility = { allowed: boolean; reason: ReplicaIneligibility | null };
export type SessionInfo = { name: string; scopes: string[]; replica: ReplicaEligibility; governance?: GovernanceCapability; enrollmentProfile?: EnrollmentProfileReceipt; pushRegistration?: PushRegistrationCapability; pushProfiles?: PushAppProfile[] };
export type SessionDataArgs = { data: JSONValue; expectedProfile?: EnrollmentProfileExpectation };
/// Host supplies HTTP status, bounded parsed JSON on 200 or null otherwise. Never derive status from error strings. Optional Retry-After delay is parsed by the host without platform clocks in core.
export type SessionReply = { status: Count; data: JSONValue; retryAfterSeconds?: Count };
export type EnrollmentPollArgs = { reply: SessionReply; expectedFingerprint: string; expectedProfile?: EnrollmentProfileExpectation };
export type EnrollmentPollState = "pending" | "approved";
/// Approved means the candidate identity was authenticated. Hosts must also require session.replica.allowed before installing it for replica use. Pending never distinguishes an unapproved token from a revoked one.
export type EnrollmentPollResult = { state: EnrollmentPollState; session: SessionInfo | null; retryAfterSeconds: Count | null };
export type SessionRevocationState = "revoked" | "unauthorized";
/// Unauthorized is not proof that an unregistered approval URL has been cancelled; a later browser approval remains possible.
export type SessionRevocationResult = { state: SessionRevocationState };
export type ReferenceSourcesArgs = { table: string };
export type ReferenceSource = { table: string; column: string; label: string; type: "ref" | "multi_ref"; incomplete: boolean };
export type ReferencedByArgs = { table: string; rowId: string; sourceTable: string; column: string; limit?: Count; offset?: Count; calendar?: CalendarContext; expectedViewUpdatedAt?: string };
export type ReferencedByPage = { source: ReferenceSource; rows: WorkspaceRow[]; nextOffset: Count | null; viewUnavailable?: string };
/// Durable submitted snapshot and unchanged hub rejection objects, not the current local row. IDs preserve exact string bytes. Re-read a full local row and use its current revision before repair; only accepted sync receipts clear the inbox.
export type RejectedEdit = { table: string; rowID: string; submitted: Row; errors: Row[] };
/// Offset pagination over the current local inbox, ordered by binary table and row ID. Default limit 100, maximum 200; default offset 0. Restart at offset 0 after sync changes the inbox; pages are not a cross-request snapshot.
export type RejectionsArgs = { limit?: Count; offset?: Count };
export type RejectionsPage = { rejections: RejectedEdit[]; nextOffset: Count | null };
export type HubCapabilities = { row_api: "v1"; schema: "none" | "full-ddl-v1"; replica_sync: boolean; subscriptions: "durable-pull-v1" | null; files: "opaque-key-v1"; conditional_patch?: "revision-v1"; subscription_features?: "scalar-lifecycle-v1"; governance?: GovernanceCapability; rowCreation?: RowCreationCapability; push_registration?: PushRegistrationCapability; push_profiles?: PushAppProfile[]; changesets?: ChangesetCapability };
/// Wire session identity. Absent capabilities are legacy only; explicit capabilities require schema full-ddl-v1 and replica_sync true before replica enrollment. Consumer enrollment still rejects admin credentials.
export type HubSession = { name: string; scopes: string[]; capabilities?: HubCapabilities };
/// HTTP 403. Canonical message and response fixture: tests/fixtures/hub-capabilities-contract.json.
export type ScopedReplicaUnsupported = { error: "scoped_replica_unsupported"; message: string };
export type SortMode = "value" | "options";
export type FilterRelative = "today";
export type FilterGroup = { match: "all" | "any"; filters: Filter[] };
export type CalendarContext = { today: string; start: string; end: string };
export type RowAction = { id: string; label: string; values: Row };
export type ViewLayoutItem = { kind: "column" | "action"; id: string };
export type RunRowActionArgs = { viewId: string; actionId: string; rowId: string; expectedUpdatedAt: string; expectedViewUpdatedAt: string };
export type SourceLinkArgs = { url: string };
export type SourceRecordDestination = { table: string; row: string };
export type SourceLinkResult = { destination?: SourceRecordDestination };
export type Target = { table: string; rowId: string };
export type Revision = { updated_at: string; hub_at: string | null };
export type NullCell = { type: "null" };
export type TextCell = { type: "text"; value: string };
export type IntegerCell = { type: "integer"; value: string };
export type RealCell = { type: "real"; value: number };
/// Typed stored cell value; integer strings preserve signed 64-bit precision. Unknown history is an outer null, distinct from a null cell.
export type CellValue = NullCell | TextCell | IntegerCell | RealCell;
export type ActorKind = "user" | "agent" | "service";
export type Actor = { principalId: string; kind: ActorKind };
export type Change = { column: string; before: CellValue; after: CellValue };
export type ConflictCode = "later_column_change" | "history_unavailable" | "revision_changed" | "validation_failed" | "proposal_changed" | "unavailable";
export type Conflict = { code: ConflictCode; column: string | null; eventIds: string[]; message: string };
export type SelectedInverseIntent = { kind: "selected_inverse"; eventIds: string[] };
export type ProposedCellChange = { column: string; after: CellValue };
export type PatchIntent = { kind: "patch"; changes: ProposedCellChange[] };
export type Intent = SelectedInverseIntent | PatchIntent;
export type PreviewRequest = { target: Target; intent: Intent };
/// Authenticated inert service preview. Its opaque token binds exact validated evidence and does not grant authority.
export type Preview = { target: Target; revision: Revision; changes: Change[]; selectedEventIds: string[]; conflicts: Conflict[]; previewToken: string | null; expiresAt: string | null };
export type HistoryEvent = { id: string; operationId: string | null; target: Target; column: string; before: CellValue | null; after: CellValue | null; occurredAt: string; actor: Actor | null; claimedOrigin: string | null; reversible: boolean; unavailableReason: string | null };
export type ProposalState = "pending" | "approved" | "rejected";
export type Proposal = { id: string; version: string; target: Target; intent: Intent; changes: Change[]; baseRevision: Revision; state: ProposalState; proposedBy: Actor; claimedOrigin: string | null; createdAt: string; updatedAt: string };
export type ApprovalReceipt = { operationId: string; proposalId: string; proposalVersion: string; target: Target; revision: Revision; historyEventIds: string[]; approvedBy: Actor; committedAt: string };
export type MutationErrorCode = "proposal_changed" | "revision_changed" | "history_unavailable" | "validation_failed" | "permission_denied" | "unavailable" | "expired_preview" | "idempotency_conflict";
/// Original-operation settlement, not the outcome of one HTTP attempt. not_committed requires a durable server record preventing this exact key/request from ever applying; other rejections remain unresolved.
export type MutationResolution = "unresolved" | "not_committed";
export type MutationError = { kind: "error"; code: MutationErrorCode; resolution: MutationResolution; conflicts: Conflict[] };
export type PurgedResult = { kind: "purged" };
export type TransportErrorCode = "offline" | "indeterminate";
/// Adapter outcome, not a service JSON response. Preserve the exact original mutation request and key on uncertain delivery.
export type TransportError = { kind: "transport_error"; code: TransportErrorCode };
export type UnavailableResult = { kind: "unavailable" };
export type ProposalSuccess = { kind: "success"; value: Proposal };
export type ApprovalSuccess = { kind: "success"; value: ApprovalReceipt };
export type ProposalMutationResult = ProposalSuccess | PurgedResult | MutationError | TransportError;
export type ApprovalResult = ApprovalSuccess | PurgedResult | MutationError | TransportError;
export type ProposalResult = ProposalSuccess | UnavailableResult | TransportError;
export type PreviewSuccess = { kind: "success"; value: Preview };
export type PreviewResult = PreviewSuccess | UnavailableResult | TransportError;
export type HistoryEventsPage = { events: HistoryEvent[]; nextCursor: string | null };
export type HistoryEventsSuccess = { kind: "success"; value: HistoryEventsPage };
export type HistoryEventsResult = HistoryEventsSuccess | UnavailableResult | TransportError;
export type ProposalsPage = { proposals: Proposal[]; nextCursor: string | null };
export type ProposalsSuccess = { kind: "success"; value: ProposalsPage };
export type ProposalsResult = ProposalsSuccess | UnavailableResult | TransportError;
export type HistoryEventsArgs = { target: Target; cursor?: string; limit?: Count };
export type CreateProposalArgs = { previewToken: string; idempotencyKey: string; claimedOrigin?: string };
export type ListProposalsArgs = { target?: Target; state?: ProposalState; cursor?: string; limit?: Count };
export type GetProposalArgs = { proposalId: string; version?: string };
export type EditProposalArgs = { proposalId: string; expectedVersion: string; previewToken: string; idempotencyKey: string; claimedOrigin?: string };
export type PreviewProposalArgs = { proposalId: string; expectedVersion: string };
export type ApproveProposalArgs = { proposalId: string; expectedVersion: string; previewToken: string; idempotencyKey: string };
export type RejectProposalArgs = { proposalId: string; expectedVersion: string; idempotencyKey: string };
export type GovernanceLimits = { maxSelectedEvents: Count; maxChangedColumns: Count; maxRequestBytes: Count; maxPageSize: Count; previewTtlSeconds: Count };
export type GovernanceAuthority = { propose: boolean; approve: boolean };
export type GovernanceCapability = { protocol: "selected-inverse-proposals-v1"; principal: Actor; authority: GovernanceAuthority; limits: GovernanceLimits; deploymentId: string; sessionId: string };
export type EnrollmentProfileReceipt = { id: string; revision: string };
export type EnrollmentProfileExpectation = { id: string; scopes: string[] };
export type CreationPolicyRef = { id: string; revision: string };
export type RowCreationCapability = { protocol: "atomic-origin-v1"; policies: CreationPolicyRef[] };
export type RowCreationTarget = { kind: "generated" | "adopted"; id: string };
export type RowCreationRequest = { policy: CreationPolicyRef; sourceId: string; occurrenceKey?: CreationOccurrenceKey; target: RowCreationTarget; updatedAt: string; values: Record<string, FilterValue> };
export type RowCreatedReceipt = { kind: "created"; policy: CreationPolicyRef; id: string; revision: Revision; originId: string };
export type RowExistingReceipt = { kind: "existing"; policy: CreationPolicyRef; id: string };
export type RowCreationReceipt = RowCreatedReceipt | RowExistingReceipt;
export type CreationOccurrenceKey = string | number;
/// Resolve one saved derived property on the bound hub, requiring the displayed row revision. Never accepts draft values or locally computes metadata.
export type ResolveDerivedArgs = { endpoint: string; table: string; id: string; column: string; expectedUpdatedAt: string };
export type DerivationFailure = { id: string; col: string; error: string; status?: number; retry_after?: number };
export type ResolveDerivedResult = { derived: number; failed: DerivationFailure[] };
/// Version 2 display settings, independent of SQL projection. Calendar uses a start date and optional inclusive end-date column. Board groups by a select property. Gallery uses an optional cover property.
export type ViewPresentation = { kind: "table" | "calendar" | "gallery" | "board"; dateColumn?: string; endDateColumn?: string; coverColumn?: string; groupColumn?: string };
export type CalendarRowsArgs = { rows: Row[]; dateColumn: string; endDateColumn?: string; days: CalendarContext[] };
export type CalendarDayRows = { date: string; rowIds: string[] };
export type CalendarRowsResult = { days: CalendarDayRows[]; undated: string[] };
export type BoardRowsArgs = { rows: Row[]; column: string; options: string[] };
export type BoardColumnRows = { value: string | null; rowIds: string[] };
export type BoardRowsResult = { columns: BoardColumnRows[] };
export type SidebarPinList = { pins: SidebarPin[]; unavailable: string | null };
export type SidebarPin = { id: string; tbl: string; position: number; updated_at: string; deleted_at: string | null; unavailable: string | null };
export type PinTableArgs = { table: string; expectedUpdatedAt: string | null };
export type UnpinTableArgs = { id: string; expectedUpdatedAt: string };
export type PinRevision = { id: string; updated_at: string };
export type MoveTablePinArgs = { id: string; direction: "up" | "down"; expected: PinRevision[] };
export type GetViewDefaultArgs = { table: string };
export type SetViewDefaultArgs = { table: string; viewId: string | null; expectedUpdatedAt: string | null };
export type ViewDefault = { table: string; viewId: string | null; updated_at: string | null; view: SavedViewRecord | null; unavailable: string | null };
export type PushAppProfile = { id: string; platform: PushPlatform };
export type PushRegistrationCapability = { protocol: string; deploymentIdentity: string; sessionBinding: string; profiles: PushAppProfile[] };
export type PushRegistrationState = { installationId: string; revision: string; state: PushRegistrationStatus; deploymentIdentity: string; sessionBinding: string; appProfile: string; activatedAfterSeq: Count; updatedAt: string };
export type PushRegistrationRequest = { appProfile: string; deviceToken: string; expectedRevision: string | null; requestId: string };
export type PushRevocationRequest = { appProfile: string; expectedRevision: string | null; requestId: string };
export type PushRegistrationReceipt = { requestId: string; registration: PushRegistrationState };
export type PushPlatform = "ios" | "macos";
export type PushRegistrationStatus = "active" | "revoked";
export type ChangesetCreate = { kind: "create"; table: string; id: string; expected_revision: null; values: Row };
export type ChangesetPatch = { kind: "patch"; table: string; id: string; expected_revision: Revision; values: Row };
export type ChangesetSoftDelete = { kind: "soft_delete"; table: string; id: string; expected_revision: Revision };
export type ChangesetOperation = ChangesetCreate | ChangesetPatch | ChangesetSoftDelete;
export type ChangesetReadSet = { table: string; where: Record<string, FilterValue>; expected: ChangesetReadMember[] };
export type ChangesetInput = { operations: ChangesetOperation[]; reads: ChangesetReadSet[] };
export type ChangesetChange = { table: string; id: string; kind: "create" | "patch" | "soft_delete"; before: Row | null; after: Row | null };
export type ChangesetPreview = { changes: ChangesetChange[]; previewToken: string; expiresAt: string };
export type ChangesetProposal = { id: string; version: string; state: ProposalState; input: ChangesetInput; changes: ChangesetChange[]; dependencies: string; proposedBy: Actor; claimedOrigin: string | null; createdAt: string; updatedAt: string };
export type ChangesetRowReceipt = { table: string; id: string; kind: "create" | "patch" | "soft_delete"; revision: Revision };
export type ChangesetApproval = { operationId: string; proposalId: string; proposalVersion: string; rows: ChangesetRowReceipt[]; historyEventIds: string[]; approvedBy: Actor; committedAt: string };
export type ChangesetPreviewSuccess = { kind: "success"; value: ChangesetPreview };
export type ChangesetPreviewResult = ChangesetPreviewSuccess | UnavailableResult | PurgedResult | MutationError | TransportError;
export type ChangesetProposalSuccess = { kind: "success"; value: ChangesetProposal };
export type ChangesetProposalResult = ChangesetProposalSuccess | UnavailableResult | PurgedResult | MutationError | TransportError;
export type ChangesetApprovalSuccess = { kind: "success"; value: ChangesetApproval };
export type ChangesetApprovalResult = ChangesetApprovalSuccess | UnavailableResult | PurgedResult | MutationError | TransportError;
export type ChangesetLimits = { maxOperations: number; maxTables: number; maxBytes: number; maxReadSets: number; maxMembershipRows: number; maxReadRows: number; previewTtlSeconds: number };
export type ChangesetCapability = { protocol: "bounded-changeset-proposals-v1"; principal: Actor; authority: GovernanceAuthority; limits: ChangesetLimits; deploymentId: string; sessionId: string };
export type ChangesetReadMember = { id: string; revision: Revision };
export type ConsumerConfig = { version: number; namespace: string; bindings: Record<string, unknown> };
export type ConsumerConfigReply = { profile: EnrollmentProfileReceipt; config: ConsumerConfig };
export type CatalogProjectionRequest = { table: string; columns: string[] };
export type CatalogProjectionOption = { v: string; d?: string; sort?: number };
export type CatalogProjectedProperty = { column: string; type: string; description: string | null; required: boolean; readOnly: boolean; options?: CatalogProjectionOption[] };
export type CatalogProjectionReply = { table: string; properties: CatalogProjectedProperty[] };
export type RowsQueryOrder = { column: string; direction: "asc" | "desc" };
export type RowsQueryRequest = { table: string; columns: string[]; filter?: unknown; order?: RowsQueryOrder[]; limit?: number; cursor?: string };
export type RowsQueryReply = { rows: Row[]; next_cursor: string | null };
export type CaptureInput = { text?: string; url?: string };
export type CaptureItem = { kind: string; id: string };
export type CaptureRequest = { request_id: string; input: CaptureInput; intent: "save" | "record_consumption"; fields?: Record<string, unknown> };
export type CaptureReceipt = { request_id: string; state: "received" | "processing" | "saved" | "needs_review" | "failed" | "uncertain"; item?: CaptureItem };
export type SQLScalar = string | number | null;
export type CalendarSlot = "today" | "start" | "end";
export type ReadPlanLiteral = { kind: "literal"; value: SQLScalar };
export type ReadPlanCalendar = { kind: "calendar"; slot: CalendarSlot };
export type ReadPlanParameter = ReadPlanLiteral | ReadPlanCalendar;
export type ReadPlanKind = "list" | "count";
export type ReadPlanCalendarPolicy = { timeZone: string; dayStartMinutes: Count };
/// Exact ordered SQL rows are collision-free structural fingerprints. Hosts compare scalar values and UTF-8 strings exactly in the same read transaction as execution; never trust metadata alone.
export type ReadPlanGuard = { kind: "schema" | "catalog" | "view" | "identity"; sql: string; parameters: SQLScalar[]; expectedRows: Row[] };
export type PrepareReadPlanArgs = { workspaceID: string; replicaID: string; table: string; kind: ReadPlanKind; viewID?: string; expectedViewUpdatedAt?: string };
export type ReadPlan = { version: Count; workspaceID: string; replicaID: string; table: string; viewID: string | null; viewUpdatedAt: string | null; kind: ReadPlanKind; sql: string; parameters: ReadPlanParameter[]; columns: string[]; displayColumn: string | null; maximumRows: Count; calendarPolicy: ReadPlanCalendarPolicy | null; guards: ReadPlanGuard[] };
export type SaveCatalogPropertyArgs = { table: string; column: string; expectedUpdatedAt: string | null; fields: Row; addColumn?: boolean };
export type SaveCatalogRuleArgs = { table: string; id: string; expectedUpdatedAt: string | null; fields: Row };
export type ResolveViewDefinitionArgs = { table: string; definition: SavedViewDefinition };
export type ResolvedViewDefinition = { definition: SavedViewDefinition; view: View };

export interface CoreOperations {
  catalog: { args: EmptyArgs; result: Catalog };
  /// columns is SQL projection and may omit id, updated_at and hidden fields; fetch a full row before editing. For visible layout only, omit columns when querying rows.
  rows: { args: View; result: WorkspaceRow[] };
  options: { args: OptionsArgs; result: string[] };
  write: { args: WriteArgs; result: Row };
  status: { args: EmptyArgs; result: SyncStatus };
  sync: { args: SyncArgs; result: SyncResult };
  serviceUsage: { args: EndpointArgs; result: UsageSummary };
  serviceNotifications: { args: EndpointArgs; result: NotificationFeed };
  markNotificationsRead: { args: NotificationReadArgs; result: NotificationReadResult };
  notificationPresentation: { args: NotificationPresentationArgs; result: NotificationPresentation };
  search: { args: SearchArgs; result: SearchHit[] };
  /// columns is SQL projection and may omit id, updated_at and hidden fields; fetch a full row before editing. For visible layout only, omit columns when querying rows.
  listViews: { args: ListViewsArgs; result: SavedViewList };
  /// expectedUpdatedAt is required when id is supplied; omit both to create a new view.
  saveView: { args: SaveViewArgs; result: SavedViewRecord };
  deleteView: { args: DeleteViewArgs; result: SavedViewRecord };
  /// Read-only advisory. Always use write for the transactionally rechecked mutation.
  writeability: { args: WriteabilityArgs; result: Writeability };
  /// One bounded hub pull with no local row, checkpoint, coverage or outbox writes. A matching durable endpoint binding and local schema are required. Remote results are read-only.
  remoteRows: { args: RemoteRowsArgs; result: RemoteRowsPage };
  /// One bounded hub pull by ID; null means no matching row. Tombstones remain explicit. A matching durable endpoint binding and local schema are required.
  remoteRow: { args: RemoteRowArgs; result: RemoteRowResult };
  /// Read this handler instance's last saved change after queued session mutations settle. Closing the workspace discards the receipt. This is not a history query or a guarantee that undo will pass current validation.
  undoStatus: { args: EmptyArgs; result: UndoStatus };
  /// Undo last saved change through the ordinary validated writer, requiring the captured revision and shape. Success consumes the receipt; failure preserves it. No redo or timestamp restoration. Hosts pause autosave and preserve newer drafts for explicit review.
  undo: { args: UndoArgs; result: Row };
  /// Pure relative approval path and public fingerprint code. Hosts validate/canonicalize the endpoint and generate/hash the candidate token; core never receives it.
  enrollmentApproval: { args: EnrollmentApprovalArgs; result: EnrollmentApproval };
  /// Pure nonadmin identity validation and current full-scope replica eligibility. Dedicated manual names are allowed. No network or storage.
  validateDeviceSession: { args: SessionDataArgs; result: SessionInfo };
  /// Pure classification of one bounded session response, matching device:<fingerprint> only on approval. Hosts own deadline/cancellation and cap the returned retry delay to remaining time; never poll after the deadline.
  enrollmentPollResult: { args: EnrollmentPollArgs; result: EnrollmentPollResult };
  /// Pure classification of session POST. Only 200 with logged_out true confirms revocation; 401 is separately unauthorized, never proof that future approval is impossible.
  sessionRevocationResult: { args: SessionReply; result: SessionRevocationResult };
  /// Incoming live catalog ref/multi_ref definitions and persisted skipped-source warnings; no source row scans. Hosts load groups lazily.
  referenceSources: { args: ReferenceSourcesArgs; result: ReferenceSource[] };
  /// One bounded local incoming-reference group. Default 20 rows, maximum 100, live sources only. Target identity uses its primary-key collation, including trashed targets. Hosts ignore stale replies and re-read a row before opening it.
  referencedBy: { args: ReferencedByArgs; result: ReferencedByPage };
  /// Read the durable local rejection inbox without initialization or mutation. Missing storage is empty; malformed persisted data fails the whole page without skipping or deleting entries. An unchanged inbox has exact terminal detection, including a full final page.
  rejections: { args: RejectionsArgs; result: RejectionsPage };
  runRowAction: { args: RunRowActionArgs; result: Row };
  /// Resolve supported external source URLs through live whole-record imported_from provenance. Missing mappings remain external; ambiguous identities fail. Hosts re-resolve the destination before guarded navigation.
  resolveSourceLink: { args: SourceLinkArgs; result: SourceLinkResult };
  /// Calls only an explicitly injected, capability-validated governance adapter. Unconfigured handlers remain unavailable; no local writer fallback.
  historyEvents: { args: HistoryEventsArgs; result: HistoryEventsResult };
  /// Calls only an explicitly injected, capability-validated governance adapter. Unconfigured handlers remain unavailable; no local writer fallback.
  previewChanges: { args: PreviewRequest; result: PreviewResult };
  /// Calls only an explicitly injected, capability-validated governance adapter. Unconfigured handlers remain unavailable; no local writer fallback.
  createProposal: { args: CreateProposalArgs; result: ProposalMutationResult };
  /// Calls only an explicitly injected, capability-validated governance adapter. Unconfigured handlers remain unavailable; no local writer fallback.
  listProposals: { args: ListProposalsArgs; result: ProposalsResult };
  /// Calls only an explicitly injected, capability-validated governance adapter. Unconfigured handlers remain unavailable; no local writer fallback.
  getProposal: { args: GetProposalArgs; result: ProposalResult };
  /// Calls only an explicitly injected, capability-validated governance adapter. Unconfigured handlers remain unavailable; no local writer fallback.
  editProposal: { args: EditProposalArgs; result: ProposalMutationResult };
  /// Calls only an explicitly injected, capability-validated governance adapter. Unconfigured handlers remain unavailable; no local writer fallback.
  previewProposal: { args: PreviewProposalArgs; result: PreviewResult };
  /// Calls only an explicitly injected, capability-validated governance adapter. Unconfigured handlers remain unavailable; no local writer fallback.
  approveProposal: { args: ApproveProposalArgs; result: ApprovalResult };
  /// Calls only an explicitly injected, capability-validated governance adapter. Unconfigured handlers remain unavailable; no local writer fallback.
  rejectProposal: { args: RejectProposalArgs; result: ProposalMutationResult };
  /// Request hub-owned derivation for an unchanged saved row. Hosts retain drafts, then sync and re-read the record; this operation never writes replica values.
  resolveDerived: { args: ResolveDerivedArgs; result: ResolveDerivedResult };
  /// Lay out already loaded rows using host-supplied civil-day bounds. All-day end dates are inclusive; timed ends exclusive, with equal start/end treated as an instant. No query, write or timezone engine.
  calendarRows: { args: CalendarRowsArgs; result: CalendarRowsResult };
  /// Group already loaded rows by a select property, preserving supplied option order and unknown stored values. No writes.
  boardRows: { args: BoardRowsArgs; result: BoardRowsResult };
  pinTable: { args: PinTableArgs; result: SidebarPinList };
  listSidebarPins: { args: EmptyArgs; result: SidebarPinList };
  unpinTable: { args: UnpinTableArgs; result: SidebarPinList };
  moveTablePin: { args: MoveTablePinArgs; result: SidebarPinList };
  getViewDefault: { args: GetViewDefaultArgs; result: ViewDefault };
  setViewDefault: { args: SetViewDefaultArgs; result: ViewDefault };
  /// Prepare a bounded read-only title-list or capped-count plan from the canonical compiler. No FTS, schema initialization, or query execution. Host owns stable workspace/replica identity, coherent publication, read-only work budget and exact guards in one read transaction.
  prepareReadPlan: { args: PrepareReadPlanArgs; result: ReadPlan };
  /// Explicit catalog mutation with the displayed revision; commits metadata and catalog_log together. Ordinary record writes remain read-only for catalog tables.
  saveCatalogProperty: { args: SaveCatalogPropertyArgs; result: Property };
  /// Explicit catalog mutation with the displayed revision; commits metadata and catalog_log together. Ordinary record writes remain read-only for catalog tables.
  saveCatalogRule: { args: SaveCatalogRuleArgs; result: Row };
  resolveViewDefinition: { args: ResolveViewDefinitionArgs; result: ResolvedViewDefinition };
  getRelatedViewDefault: { args: GetViewDefaultArgs; result: ViewDefault };
  setRelatedViewDefault: { args: SetViewDefaultArgs; result: ViewDefault };
}
export type CoreMethod = keyof CoreOperations;
export type CoreArgs<M extends CoreMethod> = CoreOperations[M]["args"];
export type CoreResult<M extends CoreMethod> = CoreOperations[M]["result"];
export type CoreHandlers = { [M in CoreMethod]: (args: CoreArgs<M>) => CoreResult<M> | Promise<CoreResult<M>> };
